/*
 * gui.java
 *
 * Created on __DATE__, __TIME__
 */

package GUI;

import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.net.Socket;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.sql.Timestamp;
import java.util.Calendar;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTree;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;

import org.apache.commons.io.FileUtils;
import org.apache.commons.io.IOUtils;
import org.apache.commons.net.ftp.FTPClient;
import org.apache.commons.net.ftp.FTPFile;
import org.omg.CORBA.PUBLIC_MEMBER;

/**
 *
 * @author  __USER__
 */
public class gui extends javax.swing.JFrame {

	//private static String server = "218.241.135.34";
	private static String server = "123.56.162.108";
	private static int port = 21;
	//private static String username = "anonymous";
	//private static String password = "";
	private static String username = "echo";
	private static String password = "123";
	public static FTPClient ftpClient = new FTPClient();
	private static String localname;
	private static File file;
	private static JTable friends;
	private static JTable friends1;

	/** Creates new form gui 
	 * @throws IOException */
	public gui() throws IOException {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 * @throws UnsupportedEncodingException 
	 * @throws IOException 
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() throws UnsupportedEncodingException {
		try {
			UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
		} catch (ClassNotFoundException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		} catch (InstantiationException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		} catch (IllegalAccessException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		} catch (UnsupportedLookAndFeelException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		jToolBar1 = new javax.swing.JToolBar();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jFormattedTextField1 = new javax.swing.JFormattedTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jPasswordField1 = new javax.swing.JPasswordField();
		jButton5 = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTree1 = new javax.swing.JTree();
		jScrollPane1 = new javax.swing.JScrollPane();
		jScrollPane4 = new javax.swing.JScrollPane();
		jScrollPane5 = new javax.swing.JScrollPane();
		menuBar = new javax.swing.JMenuBar();
		fileMenu = new javax.swing.JMenu();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jMenuItem4 = new javax.swing.JMenuItem();
		jMenuItem5 = new javax.swing.JMenuItem();
		jMenu3 = new javax.swing.JMenu();
		jMenuItem6 = new javax.swing.JMenuItem();
		jMenuItem7 = new javax.swing.JMenuItem();
		jMenu4 = new javax.swing.JMenu();
		editMenu = new javax.swing.JMenu();
		jMenu7 = new javax.swing.JMenu();
		helpMenu = new javax.swing.JMenu();
		jMenuItem8 = new javax.swing.JMenuItem();
		jMenuItem9 = new javax.swing.JMenuItem();
		jMenu5 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jToolBar1.setRollover(true);

		jButton1.setText("\u672c\u5730\u6587\u4ef6");
		jButton1.setFocusable(false);
		jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton1ActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
		jToolBar1.add(jButton1);

		jButton2.setText("\u4e0a\u4f20\u6587\u4ef6");
		jButton2.setFocusable(false);
		jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jToolBar1.add(jButton2);

		jButton3.setText("\u4e0b\u8f7d\u6587\u4ef6");
		jButton3.setFocusable(false);
		jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jToolBar1.add(jButton3);

		jButton4.setText("\u5237\u65b0");
		jButton4.setFocusable(false);
		jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton4ActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
		jToolBar1.add(jButton4);

		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jFormattedTextField1
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jFormattedTextField1ActionPerformed(evt);
					}
				});

		jLabel1.setText("\u7528\u6237\u540d");

		jLabel2.setText("\u5bc6\u7801");

		jButton5.setText("\u5feb\u901f\u767b\u5f55");

		jTextArea2.setColumns(20);
		jTextArea2.setRows(5);
		jScrollPane2.setViewportView(jTextArea2);

		jScrollPane3.setViewportView(jTree1);

		fileMenu.setText("\u6587\u4ef6");
		fileMenu.setPreferredSize(new java.awt.Dimension(50, 19));

		jMenu1.setText("\u4e0a\u4f20\u6587\u4ef6");

		jMenuItem1.setText("ABE\u4e0a\u4f20");
		jMenu1.add(jMenuItem1);

		jMenuItem2.setText("\u5b8c\u6574\u6027\u4e0a\u4f20");
		jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jMenuItem2ActionPerformed(evt);
				} catch (UnknownHostException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
		jMenu1.add(jMenuItem2);

		jMenuItem3.setText("\u7ec4\u5408\u65b9\u5f0f");
		jMenu1.add(jMenuItem3);

		fileMenu.add(jMenu1);

		jMenu2.setText("\u4e0b\u8f7d\u6587\u4ef6");

		jMenuItem4.setText("ABE\u4e0b\u8f7d");
		jMenu2.add(jMenuItem4);

		jMenuItem5.setText("\u5b8c\u6574\u6027\u4e0b\u8f7d");
		jMenu2.add(jMenuItem5);

		fileMenu.add(jMenu2);

		jMenu3.setText("\u9605\u8bfb\u6587\u4ef6");

		jMenuItem6.setText("ABE\u65b9\u5f0f\u6253\u5f00");
		jMenu3.add(jMenuItem6);

		jMenuItem7.setText("\u5728\u7ebf\u6253\u5f00");
		jMenu3.add(jMenuItem7);

		fileMenu.add(jMenu3);

		jMenu4.setText("\u6587\u4ef6\u5220\u9664");
		fileMenu.add(jMenu4);

		menuBar.add(fileMenu);

		editMenu.setText("ABE");
		editMenu.setPreferredSize(new java.awt.Dimension(50, 19));

		jMenu7.setText("Menu");
		editMenu.add(jMenu7);

		menuBar.add(editMenu);

		helpMenu.setText("\u5b8c\u6574\u6027");
		helpMenu.setPreferredSize(new java.awt.Dimension(50, 19));

		jMenuItem8.setText("\u9a8c\u8bc1\u6587\u4ef6\u5b8c\u6574\u6027");
		jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jMenuItem8ActionPerformed(evt);
				} catch (UnknownHostException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
		helpMenu.add(jMenuItem8);

		jMenuItem9.setText("\u6062\u590d\u6587\u4ef6\u5b8c\u6574\u6027");
		jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jMenuItem9ActionPerformed(evt);
				} catch (UnknownHostException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
		helpMenu.add(jMenuItem9);

		menuBar.add(helpMenu);

		jMenu5.setText("\u8bbe\u7f6e");
		menuBar.add(jMenu5);

		setJMenuBar(menuBar);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jTextField1,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														682, Short.MAX_VALUE)
												.addComponent(
														jToolBar1,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														682, Short.MAX_VALUE)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(7, 7, 7)
																.addComponent(
																		jLabel1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		45,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jFormattedTextField1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		61,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jLabel2)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jPasswordField1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		83,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jButton5))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jScrollPane4)
																				.addComponent(
																						jScrollPane1,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						307,
																						Short.MAX_VALUE))
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(36,
																										36,
																										36)
																								.addComponent(
																										jScrollPane3,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										339,
																										Short.MAX_VALUE))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jScrollPane5,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										325,
																										javax.swing.GroupLayout.PREFERRED_SIZE))))
												.addComponent(
														jScrollPane2,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														682, Short.MAX_VALUE))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jLabel2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														22,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jFormattedTextField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														23,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jPasswordField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														23,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jLabel1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														22,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jButton5))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jToolBar1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jTextField1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										33,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														157,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jScrollPane3,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														163,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(35, 35, 35)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jScrollPane4,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		188,
																		Short.MAX_VALUE)
																.addGap(40, 40,
																		40))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jScrollPane5,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		188,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
								.addComponent(jScrollPane2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(35, 35, 35)));

		pack();
		try {
			final JTree tree = new JTree(test("C:\\Users\\"));
			jScrollPane1.setViewportView(tree);
			tree.setEditable(true);
			tree.setDragEnabled(true); 
//			localname = "C:\\Users\\";
			tree.addTreeSelectionListener(new TreeSelectionListener() {
				   public void valueChanged(TreeSelectionEvent e) {
				    DefaultMutableTreeNode note = (DefaultMutableTreeNode) tree.getLastSelectedPathComponent();				   
				    localname = note.toString();//获得这个结点的名称
				    Object[][] friend = {
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""}
					};
					String[] Names = {"文件名","文件大小","文件类型","最近修改"};
					JTable table = new JTable(friend,Names);
					jScrollPane4.setViewportView(table);
					Object[][] friend1= {
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""},
							{"","","",""}
					};
					JTable table1 = new JTable(friend1,Names);
					jScrollPane5.setViewportView(table1);
					table.setShowGrid(false);
					table1.setShowGrid(false);
					//testShowlocal(localname);
					File file = new File(localname);
					File[] localFiles = file.listFiles();
					try {
						if (note.isLeaf() == true) {
							DefaultMutableTreeNode noteparent = (DefaultMutableTreeNode) note.getParent();
							String noteString = noteparent.toString()+localname;
							System.out.println(noteString);
							File file2 = new File(noteString);
							String tmpString = new String(file2.getName().getBytes("UTF-8"),"UTF-8");
							friend[0][0]= tmpString;
							friend[0][1]= file2.length();
							friend[0][2]= "wenjian";
							Calendar cal = Calendar.getInstance();
							long time = file2.lastModified();
							cal.setTimeInMillis(time);
							friend[0][3] = cal.getTime().toLocaleString();
						}
					} catch (UnsupportedEncodingException e2) {
						// TODO Auto-generated catch block
						e2.printStackTrace();
					}
					if (localFiles != null) {
						try {
							for (int i = 0; i < localFiles.length; i++) {
								if (localFiles[i].isFile() == true) {
								String tmp = localFiles[i].getName();
								String name = new String(tmp.getBytes("UTF-8"), "UTF-8");
								friend[i][0] = name;
								friend[i][1] = localFiles[i].length();
								friend[i][2] = "wenjian";
								Calendar cal = Calendar.getInstance();
								long time = localFiles[i].lastModified();
								cal.setTimeInMillis(time);
								friend[i][3] = cal.getTime().toLocaleString();}
								else if (localFiles[i].isDirectory() == true) {
									String tmp = localFiles[i].getName();
									String name = new String(tmp.getBytes("UTF-8"), "UTF-8");
									friend[i][0] = name;
									friend[i][2] = "wenjianjia";
									Calendar cal = Calendar.getInstance();
									long time = localFiles[i].lastModified();
									cal.setTimeInMillis(time);
									friend[i][3] = cal.getTime().toLocaleString();
								}
							}
						} catch (UnsupportedEncodingException e1) {
							// TODO Auto-generated catch block
							e1.printStackTrace();
						}
					}
				   // System.out.println(localname);
				   }
				  });
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}// </editor-fold>
	//GEN-END:initComponents
	/*public static void testShowlocal(String localname) throws UnsupportedEncodingException{
		String localDir = localname;
		File file = new File(localname);
		File[] localFiles = file.listFiles();
		if (localFiles != null) {
			for (int i = 0; i < localFiles.length; i++) {
				if (localFiles[i].isFile() == true) {
					String tmp = localFiles[i].getName();
					String name = new String(tmp.getBytes("UTF-8"), "UTF-8");
					friend[i][1] = name;
					
				} else if (localFiles[i].isDirectory() == true) {
					String tmp = localFiles[i].getName();
					String name = new String(tmp.getBytes("UTF-8"), "UTF-8");
				}
			}
		}
	}*/
	//注意这里需要再加上上传操作
	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt)
			throws UnknownHostException, IOException {
		String server = "123.56.162.108";
		Socket socket = new Socket(server, 7890);
		//由Socket对象得到输入流，并构造相应的BufferedReader对象  
		//BufferedReader is=new BufferedReader(new InputStreamReader(socket.getInputStream()));  
		//由Socket对象得到输出流，并构造PrintWriter对象  
		//PrintWriter os=new PrintWriter(socket.getOutputStream());  
		// System.out.println(srcFileName());
		// String stringupload = "partition&encode "+srcFileName();
		//String stringupload = "partition&encode 思科九年.txt";
		//os.println(stringupload);
		//os.flush();
		DataOutputStream dos = new DataOutputStream(socket.getOutputStream());
		//dos.writeUTF("partition&encode 思科九年.txt");
		dos.writeUTF("partition&encode 123.pdf");
		//String supload=is.readLine();  
		DataInputStream dis = new DataInputStream(socket.getInputStream());
		String receive = dis.readUTF();
		System.out.println("Server upload: " + receive);//在标准输出上打印从Server读入的字符串  
		if (receive.equals("0")) {
			jTextArea2.append("partition&encode success!");
		}
		dis.close();//关闭Socket输入流  
		dos.close();//关闭Socket输出流  
		socket.close();//关闭Socket  
	}

	private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt)
			throws UnknownHostException, IOException {
		// TODO add your handling code here:
		String server = "123.56.162.108";
		Socket socket = new Socket(server, 7890);
		//由Socket对象得到输入流，并构造相应的BufferedReader对象  
		BufferedReader is = new BufferedReader(new InputStreamReader(
				socket.getInputStream()));
		//由Socket对象得到输出流，并构造PrintWriter对象  
		PrintWriter os = new PrintWriter(socket.getOutputStream());

		String stringupload = "recoverFile|" + srcFileName();
		os.println(stringupload);
		os.flush();
		String supload = is.readLine();
		System.out.println("Server recoverFile: " + supload);//在标准输出上打印从Server读入的字符串  

		is.close();//关闭Socket输入流  
		os.close();//关闭Socket输出流  
		socket.close();//关闭Socket
	}

	private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt)
			throws UnknownHostException, IOException {
		// TODO add your handling code here:
		String server = "123.56.162.108";
		Socket socket = new Socket(server, 7890);
		//由Socket对象得到输入流，并构造相应的BufferedReader对象  
		DataOutputStream dos = new DataOutputStream(socket.getOutputStream());
		dos.writeUTF("checkIntegrity 123");
		//String supload=is.readLine();  
		DataInputStream dis = new DataInputStream(socket.getInputStream());
		String receive = dis.readUTF();
		System.out.println("Server upload: " + receive);//在标准输出上打印从Server读入的字符串  
		if (receive.equals("0")) {
			jTextArea2.append("checkIntegrity success!");
		}
		dis.close();//关闭Socket输入流  
		dos.close();//关闭Socket输出流  
		socket.close();//关闭Socket
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		testDownload();
	}

	public static void testDownload() {
		FTPClient ftpClient = new FTPClient();
		FileOutputStream fos = null;

		try {
			ftpClient.connect(server);
			ftpClient.login(username, password);
			File srcFilename = new File(jTextField1.getText().toString());
			String localFilerecover = "D:/" + srcFilename.getName();
			System.out.println("修复文件路径 " + localFilerecover);
			//String remoteFileName = "/student/" + srcFilename.getName();
			String remoteFileName = "/" + srcFilename.getName();
			//String remoteFileName = "/uftp/" + srcFilename.getName();
			fos = new FileOutputStream(localFilerecover);

			ftpClient.setBufferSize(1024);
			//设置文件类型（二进制） 
			ftpClient.setFileType(FTPClient.BINARY_FILE_TYPE);
			ftpClient.retrieveFile(remoteFileName, fos);
		} catch (IOException e) {
			e.printStackTrace();
			throw new RuntimeException("FTP客户端出错！", e);
		} finally {
			IOUtils.closeQuietly(fos);
			try {
				ftpClient.disconnect();
			} catch (IOException e) {
				e.printStackTrace();
				throw new RuntimeException("关闭FTP连接发生异常！", e);
			}
		}
		System.out.println("download success!");
		jTextArea2.append("download success!");
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
			throws IOException {
		// TODO add your handling code here:
		//if (evt.getSource().equals(jButton1)) {
		JFileChooser jfc = new JFileChooser();
		jfc.setCurrentDirectory(new File("C:\\"));
		jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
		jfc.setMultiSelectionEnabled(true);
		int state = jfc.showDialog(null, "选择");
		File f = jfc.getSelectedFile();
		System.out.println("当前选中的名字是 " + f.getName());
		jTextField1.setText(f.getCanonicalPath());

		//System.out.println(f.getAbsolutePath());
		System.out.println("当前选中的路径是 " + f.getCanonicalPath());
		//return f.getCanonicalPath();
		//}
	}

	public static String srcFileName() {
		String name = jTextField1.getName().toString();
		return name;
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		testUpload();
	}

	public static void testUpload() {
		FTPClient ftpClient = new FTPClient();
		FileInputStream fis = null;

		try {
			ftpClient.connect(server);
			ftpClient.login(username, password);
			ftpClient.enterLocalPassiveMode();
			File srcFile = new File(jTextField1.getText().toString());
			System.out.println("本地文件名 " + srcFile.getName());
			fis = new FileInputStream(srcFile);
			//设置上传目录 
			//ftpClient.changeWorkingDirectory("/student");
			ftpClient.changeWorkingDirectory("/");
			//ftpClient.changeWorkingDirectory("/uftp");
			ftpClient.setBufferSize(1024);
			ftpClient.setControlEncoding("GBK");
			//设置文件类型（二进制） 
			ftpClient.setFileType(FTPClient.BINARY_FILE_TYPE);
			String remoteFilename = srcFile.getName();
			ftpClient.storeFile(remoteFilename, fis);
		} catch (IOException e) {
			e.printStackTrace();
			throw new RuntimeException("FTP客户端出错！", e);
		} finally {
			IOUtils.closeQuietly(fis);
			try {
				ftpClient.disconnect();
			} catch (IOException e) {
				e.printStackTrace();
				throw new RuntimeException("关闭FTP连接发生异常！", e);
			}
		}
		System.out.println("upload success!");
		jTextArea2.append("upload success!");
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)
			throws IOException {
		// TODO add your handling code here:
		testupdate();
	}

	public static void testupdate() throws IOException {
		//FTPClient ftpClient = new FTPClient();
		ftpClient.connect(server);
		ftpClient.login(username, password);
		File srcFilename = new File(jTextField1.getText().toString());
		//String remoteDir = "/student";
		String remoteDir = "/";
		ftpClient.setControlEncoding("GBK");
		FTPFile[] remoteFiles = ftpClient.listFiles(remoteDir);
		String dir = "目录" + remoteDir + "下的文件:";
		//jTextArea1.append(dir + "\r\n");
		System.out.println("目录" + remoteDir + "下的文件:");
		if (remoteFiles != null) {
			for (int i = 0; i < remoteFiles.length; i++) {
				String tmp = remoteFiles[i].getName();
				String name = new String(tmp.getBytes("GBK"), "UTF-8");
				long length = remoteFiles[i].getSize();
				String readableLength = FileUtils
						.byteCountToDisplaySize(length);
				System.out.println(name + ":\t\t" + readableLength);
				String detail = name + ":\t\t" + readableLength;
				//jTextArea1.append(detail + "\r\n");
				String lenString = Long.toString(length);
			}
		}
		JTree tree = new JTree(test("/"));
		//JScrollPane jScrollPane3 = null;
		//jScrollPane3.setViewportView(tree);
		//jTextArea3.add(tree);
		//jPanel1.add(new JScrollPane(tree));
		//jFrame1.setContentPane(jPanel1);
		//jFrame1.pack();
		//jFrame1.show();
	}

	public static DefaultMutableTreeNode test(String remote) throws IOException {
		String remoteDir = remote;
		File file = new File(remote);
		ftpClient.setControlEncoding("GBK");
		File[] remoteFiles = file.listFiles();
		DefaultMutableTreeNode top = new DefaultMutableTreeNode(remoteDir);
		if (remoteFiles != null) {
			for (int i = 0; i < remoteFiles.length; i++) {
				if (remoteFiles[i].isFile() == true) {
					String tmp = remoteFiles[i].getName();
					String name = new String(tmp.getBytes("UTF-8"), "UTF-8");
					top.add(new DefaultMutableTreeNode(name));
				} else if (remoteFiles[i].isDirectory() == true) {
					String tmp = remoteFiles[i].getName();
					String name = new String(tmp.getBytes("UTF-8"), "UTF-8");
					//DefaultMutableTreeNode node = new DefaultMutableTreeNode(name);
					top.add(test(remoteDir + name + "\\"));
				}
			}
		}

		//JTree tree = new JTree(top);
		return top;
	}

	private void jFormattedTextField1ActionPerformed(
			java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					new gui().setVisible(true);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenu editMenu;
	private javax.swing.JMenu fileMenu;
	private javax.swing.JMenu helpMenu;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JFormattedTextField jFormattedTextField1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenu jMenu5;
	private javax.swing.JMenu jMenu7;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	private javax.swing.JMenuItem jMenuItem5;
	private javax.swing.JMenuItem jMenuItem6;
	private javax.swing.JMenuItem jMenuItem7;
	private javax.swing.JMenuItem jMenuItem8;
	private javax.swing.JMenuItem jMenuItem9;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private static javax.swing.JTextArea jTextArea2;
	private static javax.swing.JTextField jTextField1;
	private static Object[][] friend;
	private static Object[][] friend1;
	private javax.swing.JToolBar jToolBar1;
	private javax.swing.JTree jTree1;
	private javax.swing.JMenuBar menuBar;
	// End of variables declaration//GEN-END:variables

}